name: CustomMobs
version: 4.0
author: HellFirePvP
softdepend: [WorldEdit, WorldGuard, Multiverse-Core, MultiWorld]

main: de.hellfirepvp.CustomMobs

commands:
  cmob:
    description: Main-Cmd
    usage: /cmob
  ccmob:
    description: Console-and-Player Command
    usage: /ccmob
  cconfig:
    description: Config-Customizing Command
    usage: /cconfig
  crespawn:
    description: Respawn-Timer command
    usage: /crespawn
  ccontrol:
    description: FullControl command
    usage: /ccontrol
  cai:
    description: AI command
    usage: /cai